/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ajax.codegen.app;

import com.ajax.codegen.lib.LinkedList;

import static com.ajax.codegen.utilities.StringUtils.join;
import static com.ajax.codegen.utilities.StringUtils.split;
import static com.ajax.codegen.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
