name: Pre release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get version
      id: version
      run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
    - name: Create pre-release
      uses: actions/create-release@v1
      id: pre_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: "v${{ steps.version.outputs.version }}"
        body_path: CHANGELOG.md
    - name: Create distributions files
      run: ./gradlew :app:assembleDist
    - name: Upload zip distribution file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.pre_release.outputs.upload_url }}
        asset_path: "./app/build/distributions/codegen-cli-${{ steps.version.outputs.version }}.zip"
        asset_name: "codegen-cli-${{ steps.version.outputs.version }}.zip"
        asset_content_type: application/zip
